export const categories = [
  { name: "Kategori", icon: "▦" },
  { name: "Baju", icon: "👔" },
  { name: "Celana", icon: "👖" },
  { name: "Jaket", icon: "🧥" },
  { name: "Topi", icon: "🧢" },
  { name: "Jam", icon: "⌚" },
  { name: "Kamera", icon: "📷" },
  { name: "Handphone", icon: "📱" },
  { name: "Laptop", icon: "🖥️" },
];

export const products = [
  {
    id: 1,
    slug: "kaos-putih-hm",
    seller: "Reinger-Boyer",
    city: "Bandung",
    title: "Kaos Putih H*M",
    price: 65000,
    condition: "Baik",
    image: "/marketplace/product-1.jpg",
    avatar: "/images/avatar-1.png",
  },
  {
    id: 2,
    slug: "celana-putih",
    seller: "Hugo Beier",
    city: "Semarang",
    title: "Celana Putih",
    price: 80000,
    condition: "Baik",
    image: "/marketplace/product-2.jpg",
    avatar: "/images/avatar-2.png",
  },
  {
    id: 3,
    slug: "topi-putih",
    seller: "Davin Ahmad",
    city: "Bandung",
    title: "Topi Putih",
    price: 20000,
    condition: "Minor Damage",
    image: "/marketplace/product-3.jpg",
    avatar: "/images/avatar-3.png",
  },
  {
    id: 4,
    slug: "poco-f8-pro",
    seller: "Kenzi Sakura",
    city: "Jakarta",
    title: "POCO F8 Pro",
    price: 1120000,
    condition: "Major Damage",
    image: "/marketplace/product-4.jpg",
    avatar: "/images/avatar-4.png",
  },
  {
    id: 5,
    slug: "jaket-kulit",
    seller: "Aida Maharani",
    city: "Bogor",
    title: "Jaket Kulit",
    price: 150000,
    condition: "Baik",
    image: "/marketplace/product-5.jpg",
    avatar: "/images/avatar-5.png",
  },
  {
    id: 6,
    slug: "kaos-hitam-polos",
    seller: "Leslie Alexander",
    city: "Bogor",
    title: "Kaos Hitam Polos",
    price: 35000,
    condition: "Minor Damage",
    image: "/marketplace/product-6.jpg",
    avatar: "/images/avatar-2.png",
  },
  {
    id: 7,
    slug: "blouse-coklat",
    seller: "Aida Maharani",
    city: "Bogor",
    title: "Blouse Coklat",
    price: 150000,
    condition: "Baik",
    image: "/marketplace/product-7.jpg",
    avatar: "/images/avatar-5.png",
  },
  {
    id: 8,
    slug: "kaos-kotak-kotak",
    seller: "Kenzi Sakura",
    city: "Jakarta",
    title: "Kaos Kotak Kotak",
    price: 85000,
    condition: "Baik",
    image: "/marketplace/product-8.jpg",
    avatar: "/images/avatar-4.png",
  },
  {
    id: 9,
    slug: "polo-abu-abu",
    seller: "Hugo Beier",
    city: "Semarang",
    title: "Polo Abu Abu",
    price: 45000,
    condition: "Baik",
    image: "/marketplace/product-9.jpg",
    avatar: "/images/avatar-2.png",
  },
  {
    id: 10,
    slug: "kaos-putih-sablon",
    seller: "Reinger-Boyer",
    city: "Bandung",
    title: "Kaos Putih Sablon",
    price: 40000,
    condition: "Baik",
    image: "/marketplace/product-10.jpg",
    avatar: "/images/avatar-1.png",
  },
];

export const bajuProducts = [
  {
    id: "baju-1",
    slug: "kaos-putih-hm",
    seller: "Reinger-Boyer",
    city: "Bandung",
    title: "Kaos Putih H*M",
    price: 65000,
    condition: "Baik",
    image: "/marketplace/product-1.jpg",
    avatar: "/images/avatar-1.png",
  },
  {
    id: "baju-2",
    slug: "kemeja-coklat-baju",
    seller: "Shaun K.",
    city: "Solo",
    title: "Kemeja Coklat",
    price: 75000,
    condition: "Baik",
    image: "/marketplace/detail-main.jpg",
    avatar: "/images/avatar-2.png",
  },
  {
    id: "baju-3",
    slug: "kaos-putih-polos",
    seller: "Davin Ahmad",
    city: "Bandung",
    title: "Kaos Putih Polos",
    price: 25000,
    condition: "Minor Damage",
    image: "/marketplace/similar-3.jpg",
    avatar: "/images/avatar-3.png",
  },
  {
    id: "baju-4",
    slug: "kaos-kotak-kotak-merah",
    seller: "Kenzi Sakura",
    city: "Jakarta",
    title: "Kaos Kotak Kotak Merah",
    price: 65000,
    condition: "Baik",
    image: "/marketplace/checkout-2.jpg",
    avatar: "/images/avatar-4.png",
  },
  {
    id: "baju-5",
    slug: "kemeja-hijau",
    seller: "Aida Maharani",
    city: "Bogor",
    title: "Kemeja Hijau",
    price: 55000,
    condition: "Minor Damage",
    image: "/marketplace/similar-5.jpg",
    avatar: "/images/avatar-5.png",
  },
  {
    id: "baju-6",
    slug: "kaos-hitam-polos",
    seller: "Leslie Alexander",
    city: "Bogor",
    title: "Kaos Hitam Polos",
    price: 35000,
    condition: "Minor Damage",
    image: "/marketplace/product-6.jpg",
    avatar: "/images/avatar-2.png",
  },
  {
    id: "baju-7",
    slug: "blouse-coklat",
    seller: "Aida Maharani",
    city: "Bogor",
    title: "Blouse Coklat",
    price: 150000,
    condition: "Baik",
    image: "/marketplace/product-7.jpg",
    avatar: "/images/avatar-5.png",
  },
  {
    id: "baju-8",
    slug: "kaos-kotak-kotak",
    seller: "Kenzi Sakura",
    city: "Jakarta",
    title: "Kaos Kotak Kotak",
    price: 85000,
    condition: "Baik",
    image: "/marketplace/product-8.jpg",
    avatar: "/images/avatar-4.png",
  },
  {
    id: "baju-9",
    slug: "polo-abu-abu",
    seller: "Hugo Beier",
    city: "Semarang",
    title: "Polo Abu Abu",
    price: 45000,
    condition: "Baik",
    image: "/marketplace/product-9.jpg",
    avatar: "/images/avatar-2.png",
  },
  {
    id: "baju-10",
    slug: "kaos-putih-sablon",
    seller: "Reinger-Boyer",
    city: "Bandung",
    title: "Kaos Putih Sablon",
    price: 40000,
    condition: "Baik",
    image: "/marketplace/product-10.jpg",
    avatar: "/images/avatar-1.png",
  },
  {
    id: "baju-11",
    slug: "kemeja-putih-pria",
    seller: "Reinger-Boyer",
    city: "Bandung",
    title: "Kemeja Putih Pria",
    price: 65000,
    condition: "Baik",
    image: "/marketplace/similar-1.jpg",
    avatar: "/images/avatar-1.png",
  },
  {
    id: "baju-12",
    slug: "kemeja-maroon",
    seller: "Hugo Beier",
    city: "Semarang",
    title: "Kemeja Maroon",
    price: 65000,
    condition: "Minor Damage",
    image: "/marketplace/similar-2.jpg",
    avatar: "/images/avatar-2.png",
  },
  {
    id: "baju-13",
    slug: "kaos-putih",
    seller: "Davin Ahmad",
    city: "Bandung",
    title: "Kaos Putih",
    price: 65000,
    condition: "Baik",
    image: "/marketplace/detail-thumb-1.jpg",
    avatar: "/images/avatar-3.png",
  },
  {
    id: "baju-14",
    slug: "kaos-putih-sleeveless",
    seller: "Kenzi Sakura",
    city: "Jakarta",
    title: "Kaos Putih Sleeveless",
    price: 65000,
    condition: "Minor Damage",
    image: "/marketplace/detail-thumb-2.jpg",
    avatar: "/images/avatar-4.png",
  },
  {
    id: "baju-15",
    slug: "kaos-abu-abu",
    seller: "Aida Maharani",
    city: "Bogor",
    title: "Kaos Abu Abu",
    price: 65000,
    condition: "Baik",
    image: "/marketplace/detail-thumb-3.jpg",
    avatar: "/images/avatar-5.png",
  },
];

export const featuredProduct = {
  slug: "kemeja-coklat",
  title: "Kemeja Coklat",
  price: 90000,
  condition: "Baik, tanpa kerusakan",
  category: "Baju",
  stock: 1,
  seller: "Shaun Konopelski",
  city: "Jakarta",
  rating: "4,7 (89)",
  joined: "11 bulan lalu",
  products: "8 Produk",
  image: "/marketplace/detail-main.jpg",
  thumbnails: [
    "/marketplace/detail-thumb-1.jpg",
    "/marketplace/detail-thumb-2.jpg",
    "/marketplace/detail-thumb-3.jpg",
    "/marketplace/detail-thumb-4.jpg",
  ],
  avatar: "/images/avatar-3.png",
};

export const similarProducts = [
  {
    id: 11,
    slug: "grey-shirt",
    seller: "Reinger-Boyer",
    city: "Bandung",
    title: "Grey Shirt",
    price: 250000,
    condition: "Baik",
    image: "/marketplace/similar-1.jpg",
    avatar: "/images/avatar-1.png",
  },
  {
    id: 12,
    slug: "kemeja-california-brown",
    seller: "Hugo Beier",
    city: "Semarang",
    title: "Kemeja California Brown",
    price: 300000,
    condition: "Baik",
    image: "/marketplace/similar-2.jpg",
    avatar: "/images/avatar-2.png",
  },
  {
    id: 13,
    slug: "kemeja-lengan-pendek",
    seller: "Davin Ahmad",
    city: "Bandung",
    title: "Kemeja Lengan Pendek",
    price: 185000,
    condition: "Baik",
    image: "/marketplace/similar-3.jpg",
    avatar: "/images/avatar-3.png",
  },
  {
    id: 14,
    slug: "preloved-kemeja",
    seller: "Kenzi Sakura",
    city: "Jakarta",
    title: "Preloved Kemeja",
    price: 150000,
    condition: "Baik",
    image: "/marketplace/similar-4.jpg",
    avatar: "/images/avatar-4.png",
  },
  {
    id: 15,
    slug: "kemeja-pendek-simple",
    seller: "Aida Maharani",
    city: "Bogor",
    title: "Kemeja Pendek Simple",
    price: 175000,
    condition: "Baik",
    image: "/marketplace/similar-5.jpg",
    avatar: "/images/avatar-5.png",
  },
];

export const checkoutItems = [
  {
    id: 1,
    title: "Kemeja Coklat",
    seller: "Shaun Konopelski",
    price: 90000,
    image: "/marketplace/checkout-1.jpg",
  },
  {
    id: 2,
    title: "Kemeja Kotak Merah",
    seller: "Shaun Konopelski",
    price: 85000,
    image: "/marketplace/checkout-2.jpg",
  },
  {
    id: 3,
    title: "Celana Jeans",
    seller: "Shaun Konopelski",
    price: 100000,
    image: "/marketplace/checkout-3.jpg",
  },
];

export const allMarketplaceProducts = [
  ...products,
  ...bajuProducts,
  featuredProduct,
  ...similarProducts,
];

export function formatRupiah(value) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  })
    .format(value)
    .replace("Rp", "Rp ");
}